-- ============================================
-- Scholarships Database Schema
-- ============================================
-- Run this SQL in your Supabase SQL Editor
-- ============================================

-- Create scholarships table
CREATE TABLE IF NOT EXISTS scholarships (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  provider TEXT NOT NULL,
  amount TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'GHS',
  category TEXT NOT NULL,
  deadline DATE NOT NULL,
  location TEXT NOT NULL,
  level TEXT NOT NULL,
  description TEXT NOT NULL,
  requirements JSONB DEFAULT '[]'::jsonb,
  verified BOOLEAN DEFAULT false,
  image_url TEXT,
  featured BOOLEAN DEFAULT false,
  source TEXT, -- 'mtn', 'getfund', 'gnpc', 'other-local', 'field-based'
  website TEXT,
  email TEXT,
  phone TEXT,
  full_description TEXT,
  benefits JSONB DEFAULT '[]'::jsonb,
  eligibility JSONB DEFAULT '[]'::jsonb,
  application_process JSONB DEFAULT '[]'::jsonb,
  documents JSONB DEFAULT '[]'::jsonb,
  selection_criteria JSONB DEFAULT '[]'::jsonb,
  coverage_details JSONB DEFAULT '[]'::jsonb,
  duration TEXT,
  renewability TEXT,
  field_of_study JSONB DEFAULT '[]'::jsonb,
  faqs JSONB DEFAULT '[]'::jsonb, -- Array of {question, answer} objects
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_scholarships_source ON scholarships(source);
CREATE INDEX IF NOT EXISTS idx_scholarships_category ON scholarships(category);
CREATE INDEX IF NOT EXISTS idx_scholarships_level ON scholarships(level);
CREATE INDEX IF NOT EXISTS idx_scholarships_verified ON scholarships(verified);
CREATE INDEX IF NOT EXISTS idx_scholarships_featured ON scholarships(featured);
CREATE INDEX IF NOT EXISTS idx_scholarships_deadline ON scholarships(deadline);

-- Enable Row Level Security (RLS)
ALTER TABLE scholarships ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON scholarships
  FOR SELECT
  USING (true);

-- Create policy to allow authenticated users to insert/update/delete (for admin)
CREATE POLICY "Allow authenticated users to manage scholarships" ON scholarships
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_scholarships_updated_at
  BEFORE UPDATE ON scholarships
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- INSERT ALL EXISTING SCHOLARSHIPS
-- ============================================

-- MTN Scholarships (1)
INSERT INTO scholarships (
  id, title, provider, amount, currency, category, deadline, location, level,
  description, requirements, verified, image_url, featured, source, website, email, phone,
  full_description, benefits, eligibility, application_process, documents, selection_criteria,
  coverage_details, duration, renewability, field_of_study, faqs
) VALUES (
  'mtn-bright-scholarship',
  'MTN Ghana Foundation Bright Scholarship',
  'MTN Ghana Foundation',
  'Tuition & Academic Support',
  'GHS',
  'Need-Based',
  '2025-05-31',
  'Ghana',
  'Undergraduate & TVET',
  'Bright Scholarship from MTN Ghana Foundation supports brilliant but needy Ghanaians studying first-degree programmes and technical/vocational skills training at public tertiary institutions.',
  '["First-year or continuing student in a first-degree programme at a Ghanaian public tertiary institution, or enrolled in recognised vocational / technical skills training", "Ghanaian citizen, brilliant but needy", "Good conduct, strong academic performance and, for continuing students, extra-curricular engagement is an advantage", "No academic disciplinary issues and not serving a bond to be of good behaviour", "Not currently benefiting from any other educational scholarship"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1764597983/compressed_young-man-dressed-yellow-holding-phone-coffee-cup_puiiii.jpg',
  true,
  'mtn',
  'https://scholarship.mtn.com.gh',
  'info.mtnfoundation@mtn.com',
  '+233 24 430 0000',
  'For nearly two decades, the MTN Foundation has provided transformative scholarship support across Africa. In Ghana, the MTN Ghana Foundation Bright Scholarship focuses on brilliant but needy students who would otherwise struggle to fund their tertiary education. The scholarship targets first-degree students in public universities and technical/vocational training institutions, with a strong emphasis on STEM, ICT and future-facing disciplines such as Artificial Intelligence and Data Analytics.',
  '["Contribution towards tuition fees in line with MTN Ghana Foundation policy for the scholarship cycle", "Coverage of approved academic and registration-related charges", "Support for books and core learning materials where applicable", "Access to MTN Foundation-organised mentorship, networking and capacity-building opportunities"]'::jsonb,
  '["Must be a Ghanaian citizen and demonstrate that they are brilliant but needy", "Must be a first-year or continuing student on a first-degree programme at a Ghanaian public tertiary institution, OR enrolled in recognised vocational/technical skills training", "Continuing students must show excellent academic results and positive engagement in extra-curricular activities", "Must not have any unresolved academic disciplinary cases and must not be under a bond of good behaviour", "Must not be enjoying any other form of educational scholarship"]'::jsonb,
  '["Visit and apply online via the MTN Bright Scholarship portal at scholarship.mtn.com.gh", "Complete the online application form with accurate personal, educational and financial information", "Write and upload a one-page letter of motivation outlining your educational history, professional aspirations and reasons for needing the scholarship", "Submit the application together with valid contact details such as active phone number and email address", "Await notification from the MTN Ghana Foundation; shortlisted applicants will be contacted and invited to meet the scholarship panel"]'::jsonb,
  '["Completed online application form on scholarship.mtn.com.gh", "One-page motivation letter describing educational and professional goals", "Valid national ID or student ID as requested by the portal", "Most recent academic transcripts or result slips (for continuing students)", "Any additional supporting documents requested during the application process"]'::jsonb,
  '["Strong academic performance and potential for impact", "Demonstrated financial need and evidence of being ''brilliant but needy''", "Programme of study aligned with MTN''s focus areas such as ICT, Computer Science, Engineering, Artificial Intelligence and Data Analytics", "Gender and inclusion considerations, with priority for women and persons with disability", "Regional balance, with particular priority for applicants who lived and schooled in Bono East, Ahafo, Savannah, North East, Western North and Oti regions"]'::jsonb,
  '["Scholarship typically contributes to tuition and key academic charges as determined by MTN Ghana Foundation", "Support is provided for an academic year at a time and may be renewed subject to performance", "Non-financial benefits through mentorship, MTN engagement sessions and access to a network of Bright Scholarship alumni"]'::jsonb,
  'Normally covers one academic year at a time, renewable for the normal duration of the programme subject to performance',
  'Renewal is based on satisfactory academic performance, good conduct and continued financial need as assessed by MTN Ghana Foundation',
  '["ICT and Computer Science programmes", "Engineering disciplines", "Artificial Intelligence and Data Analytics", "Other approved programmes at public tertiary institutions and vocational/technical training centres"]'::jsonb,
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  amount = EXCLUDED.amount,
  currency = EXCLUDED.currency,
  category = EXCLUDED.category,
  deadline = EXCLUDED.deadline,
  location = EXCLUDED.location,
  level = EXCLUDED.level,
  description = EXCLUDED.description,
  requirements = EXCLUDED.requirements,
  verified = EXCLUDED.verified,
  image_url = EXCLUDED.image_url,
  featured = EXCLUDED.featured,
  source = EXCLUDED.source,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  full_description = EXCLUDED.full_description,
  benefits = EXCLUDED.benefits,
  eligibility = EXCLUDED.eligibility,
  application_process = EXCLUDED.application_process,
  documents = EXCLUDED.documents,
  selection_criteria = EXCLUDED.selection_criteria,
  coverage_details = EXCLUDED.coverage_details,
  duration = EXCLUDED.duration,
  renewability = EXCLUDED.renewability,
  field_of_study = EXCLUDED.field_of_study,
  faqs = EXCLUDED.faqs,
  updated_at = NOW();

-- GETFund Scholarships (3)
INSERT INTO scholarships (
  id, title, provider, amount, currency, category, deadline, location, level,
  description, requirements, verified, image_url, featured, source, website, email, phone,
  full_description, benefits, eligibility, application_process, documents, selection_criteria,
  coverage_details, duration, renewability, field_of_study, faqs
) VALUES
(
  'getfund-local-undergraduate',
  'Local Undergraduate Scholarship Application',
  'Ghana Education Trust Fund',
  'Varies',
  'GHS',
  'Need-Based',
  '2024-05-15',
  'Ghana',
  'Undergraduate',
  'Support for Ghana-based undergraduate studies at accredited public tertiary institutions.',
  '["Ghanaian citizenship", "Admission to accredited university", "Financial need"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392532/group-young-afro-american-female-students-dressed-black-graduation-gown-campus-as-background_gmnltc.jpg',
  true,
  'getfund',
  'https://scholarships.getfund.gov.gh/',
  'info@getfund.gov.gh',
  '+233 30 225 1234',
  'The Ghana Education Trust Fund (GETFund) Scholarship Scheme provides financial assistance to qualified Ghanaian students to pursue tertiary education both locally and abroad. The scheme aims to increase access to quality education and develop human capital for national development.',
  '["Annual scholarship award of GHS 50,000", "Partial or full tuition coverage depending on program", "Study allowance for books and materials", "Research funding for graduate students", "Access to GETFund educational programs and workshops"]'::jsonb,
  '["Must be a Ghanaian citizen with valid national ID", "Admitted to an accredited tertiary institution in Ghana or abroad", "Demonstrated financial need with supporting documentation", "Good academic standing (minimum 2nd class lower division)", "Not receiving any other full scholarship", "Bond agreement to serve Ghana after completion"]'::jsonb,
  '["Visit the GETFund website and download the application form", "Complete all sections of the application form", "Attach all required supporting documents", "Submit application to the GETFund Secretariat or online portal", "Wait for verification and assessment", "Attend interview if shortlisted", "Sign bond agreement upon selection", "Receive scholarship award letter"]'::jsonb,
  '["Completed GETFund application form", "Ghana Card or valid national identification", "Academic transcripts and certificates", "Admission letter from institution", "Two passport-size photographs", "Financial need statement", "Two recommendation letters", "Birth certificate", "Guarantor forms (for bond agreement)"]'::jsonb,
  '["Academic performance (35%)", "Financial need (35%)", "Program relevance to national development (20%)", "Interview and documentation (10%)"]'::jsonb,
  '["Up to GHS 50,000 per academic year", "Tuition contribution based on program cost", "Study allowance paid in installments", "No coverage for accommodation or living expenses"]'::jsonb,
  'Duration of undergraduate program (typically 3-4 years)',
  'Renewable annually upon satisfactory progress and compliance with bond terms',
  '["All fields of study at accredited institutions", "Priority given to STEM, Health, Education, and Agriculture"]'::jsonb,
  '[]'::jsonb
),
(
  'getfund-local-postgraduate',
  'Local Postgraduate Scholarship Application',
  'Ghana Education Trust Fund',
  'Varies',
  'GHS',
  'Need-Based',
  '2024-05-15',
  'Ghana',
  'Graduate',
  'Funding for postgraduate studies (Masters, PhD and professional programmes) within Ghana.',
  '["Ghanaian citizenship", "Admission to accredited university", "Financial need"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763129777/portrait-student-wearing-medical-mask_gokjyh.jpg',
  true,
  'getfund',
  'https://scholarships.getfund.gov.gh/',
  'info@getfund.gov.gh',
  '+233 30 225 1234',
  'The Ghana Education Trust Fund (GETFund) Scholarship Scheme provides financial assistance to qualified Ghanaian students to pursue tertiary education both locally and abroad. The scheme aims to increase access to quality education and develop human capital for national development.',
  '["Annual scholarship award of GHS 50,000", "Partial or full tuition coverage depending on program", "Study allowance for books and materials", "Research funding for graduate students", "Access to GETFund educational programs and workshops"]'::jsonb,
  '["Must be a Ghanaian citizen with valid national ID", "Admitted to an accredited tertiary institution in Ghana or abroad", "Demonstrated financial need with supporting documentation", "Good academic standing (minimum 2nd class lower division)", "Not receiving any other full scholarship", "Bond agreement to serve Ghana after completion"]'::jsonb,
  '["Visit the GETFund website and download the application form", "Complete all sections of the application form", "Attach all required supporting documents", "Submit application to the GETFund Secretariat or online portal", "Wait for verification and assessment", "Attend interview if shortlisted", "Sign bond agreement upon selection", "Receive scholarship award letter"]'::jsonb,
  '["Completed GETFund application form", "Ghana Card or valid national identification", "Academic transcripts and certificates", "Admission letter from institution", "Two passport-size photographs", "Financial need statement", "Two recommendation letters", "Birth certificate", "Guarantor forms (for bond agreement)"]'::jsonb,
  '["Academic performance (35%)", "Financial need (35%)", "Program relevance to national development (20%)", "Interview and documentation (10%)"]'::jsonb,
  '["Up to GHS 50,000 per academic year", "Tuition contribution based on program cost", "Study allowance paid in installments", "No coverage for accommodation or living expenses"]'::jsonb,
  'Duration of graduate program (typically 1-3 years)',
  'Renewable annually upon satisfactory progress and compliance with bond terms',
  '["All fields of study at accredited institutions", "Priority given to STEM, Health, Education, and Agriculture"]'::jsonb,
  '[]'::jsonb
),
(
  'getfund-foreign-postgraduate',
  'Foreign Postgraduate Scholarship Application',
  'Ghana Education Trust Fund',
  'Varies',
  'USD',
  'Merit-Based',
  '2024-05-15',
  'Foreign',
  'Graduate',
  'Limited funding support for postgraduate studies in accredited foreign universities.',
  '["Ghanaian citizenship", "Admission to foreign university", "Academic excellence"]'::jsonb,
  true,
  'https://images.unsplash.com/photo-1529074963764-98f45c47344b?q=80&w=1600&auto=format&fit=crop',
  true,
  'getfund',
  'https://scholarships.getfund.gov.gh/',
  'info@getfund.gov.gh',
  '+233 30 225 1234',
  'The Ghana Education Trust Fund (GETFund) Scholarship Scheme provides financial assistance to qualified Ghanaian students to pursue tertiary education both locally and abroad. The scheme aims to increase access to quality education and develop human capital for national development.',
  '["Annual scholarship award varies by program and destination", "Partial or full tuition coverage depending on program", "Study allowance for books and materials", "Research funding for graduate students", "Access to GETFund educational programs and workshops"]'::jsonb,
  '["Must be a Ghanaian citizen with valid national ID", "Admitted to an accredited tertiary institution abroad", "Demonstrated financial need with supporting documentation", "Good academic standing (minimum 2nd class lower division)", "Not receiving any other full scholarship", "Bond agreement to serve Ghana after completion"]'::jsonb,
  '["Visit the GETFund website and download the application form", "Complete all sections of the application form", "Attach all required supporting documents", "Submit application to the GETFund Secretariat or online portal", "Wait for verification and assessment", "Attend interview if shortlisted", "Sign bond agreement upon selection", "Receive scholarship award letter"]'::jsonb,
  '["Completed GETFund application form", "Ghana Card or valid national identification", "Academic transcripts and certificates", "Admission letter from foreign institution", "Two passport-size photographs", "Financial need statement", "Two recommendation letters", "Birth certificate", "Guarantor forms (for bond agreement)"]'::jsonb,
  '["Academic performance (35%)", "Financial need (35%)", "Program relevance to national development (20%)", "Interview and documentation (10%)"]'::jsonb,
  '["Varies by program and destination", "Tuition contribution based on program cost", "Study allowance paid in installments", "No coverage for accommodation or living expenses"]'::jsonb,
  'Duration of graduate program (typically 1-3 years)',
  'Renewable annually upon satisfactory progress and compliance with bond terms',
  '["All fields of study at accredited institutions", "Priority given to STEM, Health, Education, and Agriculture"]'::jsonb,
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  amount = EXCLUDED.amount,
  currency = EXCLUDED.currency,
  category = EXCLUDED.category,
  deadline = EXCLUDED.deadline,
  location = EXCLUDED.location,
  level = EXCLUDED.level,
  description = EXCLUDED.description,
  requirements = EXCLUDED.requirements,
  verified = EXCLUDED.verified,
  image_url = EXCLUDED.image_url,
  featured = EXCLUDED.featured,
  source = EXCLUDED.source,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  full_description = EXCLUDED.full_description,
  benefits = EXCLUDED.benefits,
  eligibility = EXCLUDED.eligibility,
  application_process = EXCLUDED.application_process,
  documents = EXCLUDED.documents,
  selection_criteria = EXCLUDED.selection_criteria,
  coverage_details = EXCLUDED.coverage_details,
  duration = EXCLUDED.duration,
  renewability = EXCLUDED.renewability,
  field_of_study = EXCLUDED.field_of_study,
  faqs = EXCLUDED.faqs,
  updated_at = NOW();

-- GNPC Scholarships (4)
INSERT INTO scholarships (
  id, title, provider, amount, currency, category, deadline, location, level,
  description, requirements, verified, image_url, featured, source, website, email, phone,
  full_description, benefits, eligibility, application_process, documents, selection_criteria,
  coverage_details, duration, renewability, field_of_study, faqs
) VALUES
(
  'gnpc-local-undergraduate',
  'Local Undergraduate Scholarship',
  'GNPC Foundation',
  'Tuition & Stipend',
  'GHS',
  'Need-Based',
  '2024-11-30',
  'Ghana',
  'Undergraduate',
  'Supports Ghanaian undergraduates admitted into accredited public tertiary institutions who demonstrate academic promise and financial need.',
  '["Ghanaian citizens with admission to a GTEC-accredited institution", "First-year or continuing students with minimum GPA 2.0"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392532/group-young-afro-american-female-students-dressed-black-graduation-gown-campus-as-background_gmnltc.jpg',
  true,
  'gnpc',
  'https://www.gnpcghana.com/gnpc-foundation',
  'info@gnpcfoundation.org',
  '+233 30 297 6100',
  'The GNPC Foundation Local Undergraduate Scholarship is designed to support brilliant but needy Ghanaian students pursuing HND and first-degree programmes in accredited public tertiary institutions. The scheme aims to increase local participation in Ghana''s petroleum industry and strategically develop human capital for national growth.',
  '["Contribution to tuition fees for the academic year", "In some cases, support for approved academic-related fees", "Opportunities for GNPC-organised capacity-building initiatives", "Part of a national pipeline of skilled personnel for the energy sector"]'::jsonb,
  '["Must be a citizen of Ghana", "Must have obtained admission into an undergraduate programme (HND / first degree) at a GTEC-accredited tertiary institution in Ghana", "First-year applicants must hold credit passes (A1–C6 in WASSCE or A–D in SSSCE) in six subjects including English, Mathematics, Integrated Science or Social Studies and three relevant electives", "Continuing students must have a minimum GPA of 2.0 and be in good academic standing", "Applicants must not be existing beneficiaries of any other scholarship scheme"]'::jsonb,
  '["Visit the GNPC Foundation scholarship portal", "Create an applicant profile and log in", "Select the Local Undergraduate Scholarship window", "Complete the online form with personal, academic, and financial details", "Upload all required documents (admission letter, WASSCE/SSSCE results, student ID, transcripts, recommendation letters, etc.)", "Review and submit your application before the deadline", "Track application status through the portal or official communication channels"]'::jsonb,
  '["Completed GNPC Foundation online application form", "Admission letter from a GTEC-accredited tertiary institution in Ghana", "WASSCE/SSSCE results slip", "Student ID card (for continuing students)", "Most recent academic transcript or statement of results", "National ID (Ghana Card or other accepted ID)", "One or two recommendation letters (academic or community leader)", "Passport-size photograph"]'::jsonb,
  '["Academic merit and performance (minimum GPA 2.0 for continuing students)", "Level of financial need based on documented evidence", "Programme relevance to national development and the energy sector", "Regional and gender balance considerations"]'::jsonb,
  '["Contribution towards tuition and approved academic fees", "Renewal typically contingent on maintaining required GPA and good conduct"]'::jsonb,
  'Normal duration of the undergraduate programme, subject to annual renewal',
  'Renewable yearly based on satisfactory academic performance and continued financial need',
  '["Science, Technology, Engineering and Mathematics (STEM)", "Health and Allied Sciences", "Education and special needs programmes", "Other fields relevant to national development"]'::jsonb,
  '[]'::jsonb
),
(
  'gnpc-local-postgraduate',
  'Local Postgraduate Scholarship',
  'GNPC Foundation',
  'Tuition & Research Support',
  'GHS',
  'Merit & Need-Based',
  '2024-12-10',
  'Ghana',
  'Postgraduate',
  'Targets graduates with at least Second Class Lower who have secured admission into postgraduate programmes in Ghana.',
  '["Ghanaian citizenship", "Admission into a postgraduate programme", "At least Second Class Lower Division"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763129777/portrait-student-wearing-medical-mask_gokjyh.jpg',
  true,
  'gnpc',
  'https://www.gnpcghana.com/gnpc-foundation',
  'info@gnpcfoundation.org',
  '+233 30 297 6100',
  'The GNPC Foundation Local Postgraduate Scholarship supports Ghanaian graduates enrolled in Masters and PhD programmes locally. The scheme channels resources into areas that strengthen the petroleum value chain and broader national development.',
  '["Contribution to tuition and approved academic fees", "Support for research-related costs where applicable", "Exposure to GNPC-related capacity-building initiatives"]'::jsonb,
  '["Must be a citizen of Ghana", "Unconditional or provisional admission into a postgraduate programme in a Ghanaian tertiary institution", "At least a Second Class Lower Division in first degree", "Programmes aligned with national development priorities, especially STEM and energy-related fields"]'::jsonb,
  '["Access the GNPC Foundation scholarship application portal", "Register and select the Local Postgraduate Scholarship track", "Fill in academic, professional and research information", "Upload admission letter, transcripts, certificates and recommendation letters", "Describe your research interest or professional focus and its relevance to national development", "Submit the application before the indicated deadline"]'::jsonb,
  '["Admission letter for the postgraduate programme", "First degree certificate and official transcript", "Curriculum Vitae (CV)", "National ID (e.g. Ghana Card)", "Two recommendation letters (academic / professional)"]'::jsonb,
  '["Quality of academic record and research potential", "Relevance of programme to petroleum industry and national priorities", "Documented financial need", "Regional, gender and inclusion considerations (including disability)"]'::jsonb,
  '["Contribution towards tuition and some academic fees", "Possible support for research work subject to approval"]'::jsonb,
  'Standard duration of the Masters/PhD programme, subject to performance',
  'Renewable annually based on academic progress and adherence to scholarship conditions',
  '["Petroleum and Energy-related disciplines", "Science, Technology, Engineering and Mathematics (STEM)", "Special needs and other priority sectors"]'::jsonb,
  '[]'::jsonb
),
(
  'gnpc-foreign-postgraduate',
  'Foreign Postgraduate Scholarship',
  'GNPC Foundation',
  'Tuition & Stipend (Varies)',
  'USD',
  'Merit-Based',
  '2024-12-31',
  'Foreign',
  'Postgraduate',
  'Provides competitive support for Ghanaians admitted into relevant Masters and PhD programmes abroad, especially in STEM and strategic areas.',
  '["Ghanaian citizenship", "Admission offer from a recognised foreign university", "At least Second Class Lower Division"]'::jsonb,
  true,
  'https://images.unsplash.com/photo-1529070538774-1843cb3265df?q=80&w=1600&auto=format&fit=crop',
  true,
  'gnpc',
  'https://www.gnpcghana.com/gnpc-foundation',
  'info@gnpcfoundation.org',
  '+233 30 297 6100',
  'The GNPC Foundation Foreign Postgraduate Scholarship supports Ghanaian graduates who obtain admission into high-quality Masters and PhD programmes abroad. The scheme focuses on building a critical mass of experts in STEM and other priority fields to support Ghana''s petroleum industry and wider economy.',
  '["Contribution towards tuition and related academic fees (amount may vary)", "Stipend support depending on destination and programme", "Support for research and thesis work in priority areas"]'::jsonb,
  '["Must be a citizen of Ghana", "Admission to a recognised foreign tertiary institution for a Masters or PhD programme", "At least Second Class Lower Division for Masters applicants", "Relevant postgraduate qualification for PhD applicants", "Preference for applicants in STEM, special needs, and strategic development fields"]'::jsonb,
  '["Obtain an admission letter from a recognised foreign university", "Prepare academic transcripts, certificates and research proposal (for PhD)", "Access the GNPC Foundation foreign scholarship portal", "Complete the online application form for Masters/PhD (Foreign)", "Upload CV, recommendation letters, admission letter and research proposal/thesis (for PhD)", "Submit within the published application window"]'::jsonb,
  '["Admission letter from foreign university", "First and second degree certificates as applicable", "Academic transcripts", "Curriculum Vitae (CV)", "Letters of recommendation (academic and occupational)", "Research proposal or thesis synopsis (PhD only)", "National Service certificate", "Passport photograph and valid national ID"]'::jsonb,
  '["Academic excellence and research potential", "Relevance of field of study to Ghana''s petroleum industry and development agenda", "Preference for tuition-free or partially funded universities", "Consideration for lecturers in public tertiary institutions and persons with disability"]'::jsonb,
  '["Level of support may vary depending on programme, destination and existing funding", "Typically contributes to tuition, with possible stipend support"]'::jsonb,
  'Normal length of the foreign Masters/PhD programme',
  'Subject to satisfactory academic progress reports and continued alignment with scholarship terms',
  '["Science, Technology, Engineering and Mathematics (STEM)", "Energy, Petroleum and related disciplines", "Special needs and other approved strategic areas"]'::jsonb,
  '[]'::jsonb
),
(
  'gnpc-capacity-building',
  'Capacity Building & Professional Development',
  'GNPC Foundation',
  'Varies',
  'GHS',
  'Professional Development',
  '2024-12-31',
  'Ghana',
  'Professional',
  'Short-term programmes and certifications to deepen expertise for public servants and professionals supporting the energy sector and wider economy.',
  '["Public servants and professionals", "Skills upgrade needs", "Aligned with national development"]'::jsonb,
  true,
  'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=1600&auto=format&fit=crop',
  false,
  'gnpc',
  'https://www.gnpcghana.com/gnpc-foundation',
  'info@gnpcfoundation.org',
  '+233 30 297 6100',
  'Short-term programmes and certifications to deepen expertise for public servants and professionals supporting the energy sector and wider economy.',
  '["Structured for knowledge and skills upgrade", "Focus on public servants and key sector professionals", "Programmes aligned to national development needs", "Strengthens local participation in the petroleum value chain"]'::jsonb,
  '["Public servants and professionals", "Skills upgrade needs", "Aligned with national development"]'::jsonb,
  '["Check GNPC Foundation website for available programmes", "Review eligibility and application requirements", "Submit application through official channels", "Attend selection interviews if required"]'::jsonb,
  '["Completed application form", "Professional CV", "Recommendation letters", "Evidence of current role and responsibilities"]'::jsonb,
  '["Professional relevance to energy sector", "Potential impact on national development", "Commitment to knowledge transfer"]'::jsonb,
  '["Varies by programme", "May include tuition, materials, and accommodation"]'::jsonb,
  'Varies by programme',
  'Subject to programme terms',
  '["Energy and Petroleum", "Public Administration", "Engineering and Technical Skills"]'::jsonb,
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  amount = EXCLUDED.amount,
  currency = EXCLUDED.currency,
  category = EXCLUDED.category,
  deadline = EXCLUDED.deadline,
  location = EXCLUDED.location,
  level = EXCLUDED.level,
  description = EXCLUDED.description,
  requirements = EXCLUDED.requirements,
  verified = EXCLUDED.verified,
  image_url = EXCLUDED.image_url,
  featured = EXCLUDED.featured,
  source = EXCLUDED.source,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  full_description = EXCLUDED.full_description,
  benefits = EXCLUDED.benefits,
  eligibility = EXCLUDED.eligibility,
  application_process = EXCLUDED.application_process,
  documents = EXCLUDED.documents,
  selection_criteria = EXCLUDED.selection_criteria,
  coverage_details = EXCLUDED.coverage_details,
  duration = EXCLUDED.duration,
  renewability = EXCLUDED.renewability,
  field_of_study = EXCLUDED.field_of_study,
  faqs = EXCLUDED.faqs,
  updated_at = NOW();

-- Other Local Scholarships (4) - Ghana Scholarships Secretariat
INSERT INTO scholarships (
  id, title, provider, amount, currency, category, deadline, location, level,
  description, requirements, verified, image_url, featured, source, website, email, phone,
  full_description, benefits, eligibility, application_process, documents, selection_criteria,
  coverage_details, duration, renewability, field_of_study, faqs
) VALUES
(
  'national-merit',
  'National Merit Scholarships',
  'Ghana Scholarships Secretariat',
  'Varies',
  'GHS',
  'Merit & Need-Based',
  '2024-12-31',
  'Ghana · All Regions',
  'Undergraduate',
  'Core national scholarship awards for brilliant but needy Ghanaians at the tertiary level. Focused on academic excellence, leadership potential and equity across districts.',
  '["High-performing students from SHS into tertiary", "Accredited public and private institutions"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392532/group-young-afro-american-female-students-dressed-black-graduation-gown-campus-as-background_gmnltc.jpg',
  true,
  'other-local',
  'https://scholarships.gov.gh',
  'info@scholarships.gov.gh',
  '+233 30 222 0000',
  'Core national scholarship awards for brilliant but needy Ghanaians at the tertiary level. Focused on academic excellence, leadership potential and equity across districts.',
  '["Targets high-performing students from SHS into tertiary", "Supports students in accredited public and private institutions", "Considers both academic records and financial need", "Aligns with Ghana''s long-term human capital development goals"]'::jsonb,
  '["High-performing students from SHS into tertiary", "Accredited public and private institutions"]'::jsonb,
  '["Visit scholarships.gov.gh", "Check for application windows", "Complete online application", "Submit required documents", "Attend district-level interviews"]'::jsonb,
  '["Completed application form", "Academic transcripts", "Admission letter", "National ID", "Recommendation letters"]'::jsonb,
  '["Academic excellence", "Financial need", "Leadership potential", "Regional balance"]'::jsonb,
  '["Varies by scholarship type", "May cover tuition and academic fees"]'::jsonb,
  'Varies',
  'Subject to annual review',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
),
(
  'local-tertiary',
  'Local Tertiary Scholarships',
  'Ghana Scholarships Secretariat',
  'Varies',
  'GHS',
  'Need-Based',
  '2024-05-15',
  'Universities, Technical Universities, Colleges',
  'Undergraduate',
  'Covers tuition and approved academic-related costs for students attending accredited tertiary institutions within Ghana.',
  '["Open to students in NAB / GTEC accredited institutions", "Continuing & fresh students apply within specific annual windows"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392517/medium-shot-students-classroom_bn5nbl.jpg',
  true,
  'other-local',
  'https://scholarships.gov.gh',
  'info@scholarships.gov.gh',
  '+233 30 222 0000',
  'Covers tuition and approved academic-related costs for students attending accredited tertiary institutions within Ghana.',
  '["Open to students in NAB / GTEC accredited institutions", "Includes universities, technical universities and polytechnics", "Also covers nursing, teacher training and agriculture colleges", "Continuing & fresh students apply within specific annual windows"]'::jsonb,
  '["Open to students in NAB / GTEC accredited institutions", "Continuing & fresh students apply within specific annual windows"]'::jsonb,
  '["Visit scholarships.gov.gh", "Create account with registration code from institution", "Complete online form", "Upload admission letter, transcripts, certificates", "Take online aptitude test", "Attend district interview"]'::jsonb,
  '["Completed online application", "Admission letter", "Academic transcripts", "Student ID", "National ID", "Passport photos"]'::jsonb,
  '["Academic performance", "Financial need", "Institution accreditation", "District balance"]'::jsonb,
  '["Tuition and approved academic-related costs", "Continuing students: 1 April – 15 May", "Late-admitted new students: 1–30 September"]'::jsonb,
  'Normal duration of program',
  'Renewable annually based on performance',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
),
(
  'district-level',
  'District-Level Scholarships',
  'Ghana Scholarships Secretariat',
  'Varies',
  'GHS',
  'Need-Based',
  '2024-12-31',
  'District Scholarship Committees',
  'Undergraduate',
  'A decentralised scholarship system where applicants are vetted, interviewed and selected at the district level to ensure fairness and inclusion.',
  '["Applications tied to your district of residence or schooling", "District panels conduct interviews and shortlisting"]'::jsonb,
  true,
  'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?q=80&w=1600&auto=format&fit=crop',
  true,
  'other-local',
  'https://scholarships.gov.gh',
  'info@scholarships.gov.gh',
  '+233 30 222 0000',
  'A decentralised scholarship system where applicants are vetted, interviewed and selected at the district level to ensure fairness and inclusion.',
  '["Applications tied to your district of residence or schooling", "District panels conduct interviews and shortlisting", "Details verified directly with your institution", "Designed to spread opportunity beyond major cities"]'::jsonb,
  '["Applications tied to your district of residence or schooling", "District panels conduct interviews and shortlisting"]'::jsonb,
  '["Complete online application", "Select your district", "Submit required documents", "Attend district interview panel", "Await selection results"]'::jsonb,
  '["Completed application form", "District residence proof", "Academic documents", "Institution verification", "Interview confirmation"]'::jsonb,
  '["District residence or schooling", "Academic merit", "Financial need", "Interview performance"]'::jsonb,
  '["Varies by district allocation", "May cover tuition and fees"]'::jsonb,
  'Varies',
  'Subject to district review',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
),
(
  'foreign-tertiary',
  'Foreign Tertiary Scholarships',
  'Ghana Scholarships Secretariat',
  'Varies',
  'USD',
  'Merit-Based',
  '2024-12-31',
  'Partner Countries & Institutions',
  'Graduate',
  'Scholarship offers received under Bilateral Cooperation Agreements for Ghanaian students to pursue undergraduate and postgraduate studies abroad.',
  '["Managed in partnership with Ministry of Foreign Affairs & Regional Integration", "Includes interviews and committee-based selection"]'::jsonb,
  true,
  'https://images.unsplash.com/photo-1529070538774-1843cb3265df?q=80&w=1600&auto=format&fit=crop',
  true,
  'other-local',
  'https://scholarships.gov.gh',
  'info@scholarships.gov.gh',
  '+233 30 222 0000',
  'Scholarship offers received under Bilateral Cooperation Agreements for Ghanaian students to pursue undergraduate and postgraduate studies abroad.',
  '["Managed in partnership with Ministry of Foreign Affairs & Regional Integration", "Publicity via Scholarships Secretariat website and national media", "Includes interviews and committee-based selection", "Awarding country gives final approval and issues offers"]'::jsonb,
  '["Managed in partnership with Ministry of Foreign Affairs & Regional Integration", "Includes interviews and committee-based selection"]'::jsonb,
  '["Check Scholarships Secretariat website for calls", "Apply through official portal", "Attend selection interviews", "Receive country approval", "Accept scholarship offer"]'::jsonb,
  '["Completed application", "Academic transcripts", "Admission letter from foreign institution", "Recommendation letters", "Passport", "Medical certificates"]'::jsonb,
  '["Academic excellence", "Program relevance", "Bilateral agreement terms", "Interview performance"]'::jsonb,
  '["Varies by bilateral agreement", "May include tuition, stipend, accommodation"]'::jsonb,
  'Varies by program',
  'Subject to agreement terms',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  amount = EXCLUDED.amount,
  currency = EXCLUDED.currency,
  category = EXCLUDED.category,
  deadline = EXCLUDED.deadline,
  location = EXCLUDED.location,
  level = EXCLUDED.level,
  description = EXCLUDED.description,
  requirements = EXCLUDED.requirements,
  verified = EXCLUDED.verified,
  image_url = EXCLUDED.image_url,
  featured = EXCLUDED.featured,
  source = EXCLUDED.source,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  full_description = EXCLUDED.full_description,
  benefits = EXCLUDED.benefits,
  eligibility = EXCLUDED.eligibility,
  application_process = EXCLUDED.application_process,
  documents = EXCLUDED.documents,
  selection_criteria = EXCLUDED.selection_criteria,
  coverage_details = EXCLUDED.coverage_details,
  duration = EXCLUDED.duration,
  renewability = EXCLUDED.renewability,
  field_of_study = EXCLUDED.field_of_study,
  faqs = EXCLUDED.faqs,
  updated_at = NOW();

-- Field-Based Scholarships (12 from ScholarshipHub.tsx)
INSERT INTO scholarships (
  id, title, provider, amount, currency, category, deadline, location, level,
  description, requirements, verified, image_url, featured, source, website, email, phone,
  full_description, benefits, eligibility, application_process, documents, selection_criteria,
  coverage_details, duration, renewability, field_of_study, faqs
) VALUES
(
  'mastercard-foundation',
  'Mastercard Foundation Scholars Program',
  'Mastercard Foundation',
  'Full Tuition',
  'USD',
  'Merit-Based',
  '2024-12-31',
  'Ghana',
  'Undergraduate',
  'Comprehensive scholarship covering tuition, accommodation, and living expenses for outstanding students.',
  '["Minimum GPA 3.5", "Financial need", "Leadership potential"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392517/medium-shot-students-classroom_bn5nbl.jpg',
  true,
  'field-based',
  'https://mastercardfdn.org/scholars-program/',
  'scholars@mastercardfdn.org',
  '+233 30 278 0300',
  'The Mastercard Foundation Scholars Program is a comprehensive scholarship initiative that identifies and supports academically talented young people from disadvantaged communities across Africa. The program provides financial support, mentorship, and leadership development opportunities to help scholars achieve their full potential and become transformative leaders in their communities.',
  '["Full tuition coverage for the entire program duration", "Accommodation expenses (on-campus or off-campus housing)", "Monthly living allowance for food and personal expenses", "Textbooks and learning materials", "Health insurance coverage", "Leadership development workshops and training", "Mentorship from industry professionals", "Networking opportunities with global scholars", "Career development and internship support", "Alumni network access after graduation"]'::jsonb,
  '["Must be a citizen of an African country", "Demonstrated academic excellence (minimum GPA 3.5 on a 4.0 scale)", "Evidence of financial need", "Strong leadership potential and community involvement", "Must have received admission to a partner university", "Age 18-25 at the time of application", "Proficiency in English (for English-taught programs)", "Commitment to returning to Africa after studies to contribute to development"]'::jsonb,
  '["Visit the official Mastercard Foundation Scholars Program website", "Create an account on the application portal", "Complete the online application form with personal details", "Upload all required documents (transcripts, recommendation letters, etc.)", "Write and submit required essays on leadership and community impact", "Submit the application before the deadline", "Participate in interviews if shortlisted", "Accept the scholarship offer if selected"]'::jsonb,
  '["Completed online application form", "Academic transcripts from secondary school and any post-secondary education", "Admission letter from a partner university", "Two recommendation letters (one academic, one community-based)", "Personal statement and leadership essays", "Proof of financial need (family income statements, etc.)", "Valid passport or national ID", "Passport-size photographs"]'::jsonb,
  '["Academic excellence and potential", "Demonstrated financial need", "Leadership qualities and community engagement", "Commitment to social change and development", "Alignment with program values and goals"]'::jsonb,
  '["Full tuition fees for the entire program", "Accommodation and housing support", "Monthly living stipend", "Books and learning materials", "Health insurance", "Travel allowance (if applicable)", "Leadership and professional development programs"]'::jsonb,
  'Full duration of undergraduate program (typically 3-4 years)',
  'Renewable annually based on academic performance and program participation',
  '["Engineering & Technology", "Health Sciences & Medicine", "Business & Economics", "Agriculture & Environmental Sciences", "Education", "Social Sciences"]'::jsonb,
  '[]'::jsonb
),
(
  'chevening',
  'Chevening Scholarships',
  'UK Government',
  'Full Coverage',
  'GBP',
  'Merit-Based',
  '2024-10-31',
  'United Kingdom',
  'Graduate',
  'Fully-funded scholarships for one-year Master''s degrees at UK universities.',
  '["2+ years work experience", "Bachelor''s degree", "English proficiency"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392704/portrait-young-woman-with-laptop-hands-outside-school_yktf28.jpg',
  true,
  'field-based',
  'https://www.chevening.org',
  'chevening@fco.gov.uk',
  '+44 20 7008 1500',
  'Chevening Scholarships are the UK government''s global scholarship programme, funded by the Foreign, Commonwealth and Development Office (FCDO) and partner organisations. The scholarships support study at UK universities for individuals with demonstrable leadership potential who will shape the future of their countries across the world.',
  '["Full tuition fees for one-year Master''s program", "Monthly living allowance (stipend)", "Round-trip airfare to the UK", "Arrival allowance", "Homeward departure allowance", "Cost of one visa application", "Travel grant to attend Chevening events in the UK", "Access to exclusive Chevening alumni network", "Professional networking events and opportunities"]'::jsonb,
  '["Citizen of a Chevening-eligible country", "Hold an undergraduate degree that enables entry to a postgraduate program at a UK university", "Have at least two years (2,800 hours) of work experience", "Apply to three different eligible UK university courses and receive an unconditional offer from one", "Meet the Chevening English language requirement", "Not hold British or dual British citizenship", "Not be a current employee or ex-employee of FCDO or FCDO sponsored organizations", "Return to your country of citizenship for a minimum of two years after scholarship ends"]'::jsonb,
  '["Check eligibility on the Chevening website", "Create an account on the Chevening application system", "Complete the online application form (personal details, work experience, study plan)", "Select three UK university courses you wish to apply to", "Write four essays (Leadership, Networking, Study Plans, Career Plans)", "Provide two references", "Submit application before November 7 deadline", "Apply to your chosen UK universities (conditional offers accepted)", "If shortlisted, attend interview at British Embassy/High Commission", "Receive final scholarship decision in June"]'::jsonb,
  '["Valid passport", "Academic transcripts and degree certificates", "Two reference letters", "English language test results (IELTS, TOEFL, etc.)", "University conditional offer letters", "Work experience certificates and CV", "Essay responses (submitted online)", "No financial documents required"]'::jsonb,
  '["Leadership and influence (essential)", "Networking skills and relationship building (essential)", "Academic excellence and study plan (important)", "Career trajectory and impact potential (important)", "Interview performance (final stage)"]'::jsonb,
  '["Full tuition fees (no upper limit)", "Monthly stipend of approximately £1,236", "Economy class return airfare", "£1,500 arrival allowance", "£1,250 departure allowance", "Visa application fee", "Travel costs for mandatory events"]'::jsonb,
  'One academic year (Master''s degree program)',
  'Non-renewable. Scholars must return home for 2 years before being eligible for another Chevening award',
  '["Business & Economics", "Social Sciences", "Arts & Humanities", "Law & Legal Studies"]'::jsonb,
  '[]'::jsonb
),
(
  'fulbright',
  'Fulbright Foreign Student Program',
  'US Department of State',
  'Full Coverage',
  'USD',
  'Merit-Based',
  '2024-09-30',
  'United States',
  'Graduate',
  'Fully-funded scholarships for graduate study in the United States.',
  '["Bachelor''s degree", "English proficiency", "Academic excellence"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392935/19234_tbfzs9.jpg',
  false,
  'field-based',
  'https://foreign.fulbrightonline.org',
  'fulbright@state.gov',
  '+1 202 632 3238',
  'The Fulbright Program is the flagship international educational exchange program sponsored by the U.S. government and is designed to increase mutual understanding between the people of the United States and the people of other countries.',
  '["Full tuition and fees", "Monthly living stipend", "Round-trip airfare", "Health insurance", "Book and research allowance", "Enrichment activities and cultural programs"]'::jsonb,
  '["Bachelor''s degree or equivalent", "English proficiency", "Academic excellence", "Leadership potential", "Commitment to return home after program"]'::jsonb,
  '["Check eligibility requirements", "Complete online application", "Submit academic transcripts", "Provide recommendation letters", "Write personal statement", "Attend interview if shortlisted"]'::jsonb,
  '["Completed application form", "Academic transcripts", "Degree certificates", "Recommendation letters", "English test scores", "Personal statement"]'::jsonb,
  '["Academic merit", "Leadership potential", "Program fit", "Interview performance"]'::jsonb,
  '["Full tuition and fees", "Monthly stipend", "Airfare", "Health insurance"]'::jsonb,
  '1-2 years depending on program',
  'Non-renewable',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
),
(
  'daad',
  'DAAD Scholarships',
  'German Academic Exchange Service',
  '850',
  'EUR',
  'Merit-Based',
  '2024-10-15',
  'Germany',
  'Graduate',
  'Monthly stipend and tuition coverage for Master''s and PhD programs in Germany.',
  '["Bachelor''s degree", "Academic excellence", "Research proposal"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392517/medium-shot-students-classroom_bn5nbl.jpg',
  false,
  'field-based',
  'https://www.daad.de',
  'info@daad.de',
  '+49 228 882-0',
  'DAAD (Deutscher Akademischer Austauschdienst) offers scholarships for international students to study and conduct research in Germany.',
  '["Monthly stipend of €850-1,200", "Tuition fee coverage", "Health insurance", "Travel allowance", "Research allowance"]'::jsonb,
  '["Bachelor''s degree", "Academic excellence", "Research proposal", "Language proficiency (German or English depending on program)"]'::jsonb,
  '["Check DAAD website for programs", "Complete online application", "Submit research proposal", "Provide academic documents", "Attend interview if required"]'::jsonb,
  '["Completed application", "Academic transcripts", "Degree certificates", "Research proposal", "Recommendation letters", "Language certificates"]'::jsonb,
  '["Academic excellence", "Research quality", "Program fit", "Language skills"]'::jsonb,
  '["Monthly stipend", "Tuition coverage", "Health insurance", "Travel allowance"]'::jsonb,
  '1-3 years depending on program',
  'Renewable based on performance',
  '["Engineering & Technology", "Natural Sciences", "Computer Science & IT"]'::jsonb,
  '[]'::jsonb
),
(
  'commonwealth',
  'Commonwealth Scholarships',
  'Commonwealth Scholarship Commission',
  'Full Coverage',
  'GBP',
  'Merit-Based',
  '2024-12-01',
  'United Kingdom',
  'Graduate',
  'Fully-funded scholarships for Master''s and PhD programs in the UK.',
  '["Commonwealth citizen", "Bachelor''s degree", "Academic excellence"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392532/group-young-afro-american-female-students-dressed-black-graduation-gown-campus-as-background_gmnltc.jpg',
  false,
  'field-based',
  'https://cscuk.fcdo.gov.uk',
  'info@cscuk.org.uk',
  '+44 20 7380 6700',
  'Commonwealth Scholarships enable talented and motivated individuals to gain the knowledge and skills required for sustainable development.',
  '["Full tuition fees", "Monthly stipend", "Airfare", "Thesis grant", "Warm clothing allowance"]'::jsonb,
  '["Commonwealth citizen", "Bachelor''s degree", "Academic excellence", "Commitment to development"]'::jsonb,
  '["Apply through national nominating agency", "Complete application form", "Submit academic documents", "Attend interview", "Receive nomination"]'::jsonb,
  '["Completed application", "Academic transcripts", "Degree certificates", "Recommendation letters", "Research proposal"]'::jsonb,
  '["Academic merit", "Development impact", "Leadership potential"]'::jsonb,
  '["Full tuition", "Monthly stipend", "Airfare", "Thesis grant"]'::jsonb,
  '1-3 years',
  'Renewable based on performance',
  '["Health Sciences & Medicine", "Education", "Social Sciences"]'::jsonb,
  '[]'::jsonb
),
(
  'erasmus-mundus',
  'Erasmus Mundus Scholarships',
  'European Union',
  'Full Coverage',
  'EUR',
  'Merit-Based',
  '2024-11-20',
  'Europe',
  'Graduate',
  'Joint Master''s and PhD programs across multiple European universities.',
  '["Bachelor''s degree", "Academic excellence", "Language proficiency"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392704/portrait-young-woman-with-laptop-hands-outside-school_yktf28.jpg',
  false,
  'field-based',
  'https://www.erasmusplus.org',
  'erasmus@ec.europa.eu',
  '+32 2 299 11 11',
  'Erasmus Mundus Joint Master Degrees (EMJMD) are prestigious international study programs, jointly designed and delivered by a group of higher education institutions.',
  '["Full tuition fees", "Monthly allowance", "Travel costs", "Installation costs"]'::jsonb,
  '["Bachelor''s degree", "Academic excellence", "Language proficiency", "Program-specific requirements"]'::jsonb,
  '["Check available programs", "Apply directly to program", "Submit academic documents", "Attend interviews if required"]'::jsonb,
  '["Completed application", "Academic transcripts", "Degree certificates", "Language certificates", "Recommendation letters"]'::jsonb,
  '["Academic merit", "Program fit", "Language skills", "Interview performance"]'::jsonb,
  '["Full tuition", "Monthly allowance", "Travel costs", "Installation costs"]'::jsonb,
  '1-2 years',
  'Non-renewable',
  '["Engineering & Technology", "Business & Economics", "Arts & Humanities"]'::jsonb,
  '[]'::jsonb
),
(
  'auf',
  'Agence Universitaire de la Francophonie',
  'AUF',
  'Full Coverage',
  'EUR',
  'Merit-Based',
  '2024-10-10',
  'France',
  'Graduate',
  'Scholarships for French-speaking students pursuing higher education.',
  '["French proficiency", "Bachelor''s degree", "Academic excellence"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392935/19234_tbfzs9.jpg',
  false,
  'field-based',
  'https://www.auf.org',
  'info@auf.org',
  '+33 1 44 37 33 00',
  'AUF offers scholarships for French-speaking students to study in French-speaking countries.',
  '["Tuition coverage", "Monthly stipend", "Travel allowance", "Health insurance"]'::jsonb,
  '["French proficiency", "Bachelor''s degree", "Academic excellence", "French-speaking country citizenship"]'::jsonb,
  '["Check AUF website", "Complete application", "Submit documents", "Attend interview"]'::jsonb,
  '["Completed application", "Academic transcripts", "French language certificate", "Recommendation letters"]'::jsonb,
  '["Academic merit", "French proficiency", "Program fit"]'::jsonb,
  '["Tuition coverage", "Monthly stipend", "Travel allowance"]'::jsonb,
  '1-3 years',
  'Renewable based on performance',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
),
(
  'rhodes',
  'Rhodes Scholarships',
  'Rhodes Trust',
  'Full Coverage',
  'GBP',
  'Merit-Based',
  '2024-10-15',
  'United Kingdom',
  'Graduate',
  'World''s oldest and most prestigious international scholarship program.',
  '["Academic excellence", "Leadership potential", "Service to others"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392517/medium-shot-students-classroom_bn5nbl.jpg',
  true,
  'field-based',
  'https://www.rhodeshouse.ox.ac.uk',
  'info@rhodeshouse.ox.ac.uk',
  '+44 1865 270902',
  'Rhodes Scholarships are postgraduate awards supporting exceptional young people from around the world to study at the University of Oxford.',
  '["Full tuition and fees", "Living stipend", "Travel costs", "Health insurance"]'::jsonb,
  '["Academic excellence", "Leadership potential", "Service to others", "Age 18-28", "Bachelor''s degree"]'::jsonb,
  '["Check eligibility", "Complete application", "Submit essays", "Attend regional interviews", "Final selection at Oxford"]'::jsonb,
  '["Completed application", "Academic transcripts", "Personal statement", "Recommendation letters", "CV"]'::jsonb,
  '["Academic excellence", "Leadership", "Character", "Service commitment"]'::jsonb,
  '["Full tuition", "Living stipend", "Travel costs", "Health insurance"]'::jsonb,
  '2-3 years',
  'Non-renewable',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
),
(
  'gates-cambridge',
  'Gates Cambridge Scholarships',
  'Bill & Melinda Gates Foundation',
  'Full Coverage',
  'GBP',
  'Merit-Based',
  '2024-10-11',
  'United Kingdom',
  'Graduate',
  'Full-cost scholarships for outstanding applicants from outside the UK.',
  '["Academic excellence", "Leadership potential", "Commitment to improving lives"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392532/group-young-afro-american-female-students-dressed-black-graduation-gown-campus-as-background_gmnltc.jpg',
  true,
  'field-based',
  'https://www.gatescambridge.org',
  'info@gatescambridge.org',
  '+44 1223 338467',
  'Gates Cambridge Scholarships are full-cost awards for outstanding applicants from countries outside the UK to pursue a full-time postgraduate degree in any subject available at the University of Cambridge.',
  '["Full tuition fees", "Maintenance allowance", "Airfare", "Immigration health surcharge", "Academic development funding"]'::jsonb,
  '["Academic excellence", "Leadership potential", "Commitment to improving lives", "Admission to Cambridge", "Non-UK citizen"]'::jsonb,
  '["Apply to Cambridge University", "Complete Gates Cambridge application", "Submit essays", "Attend interview", "Receive decision"]'::jsonb,
  '["Cambridge application", "Academic transcripts", "Personal statement", "Research proposal", "Recommendation letters"]'::jsonb,
  '["Academic excellence", "Leadership", "Commitment to improving lives", "Fit with Cambridge"]'::jsonb,
  '["Full tuition", "Maintenance allowance", "Airfare", "Health surcharge"]'::jsonb,
  '1-4 years depending on program',
  'Renewable based on performance',
  '["All Fields"]'::jsonb,
  '[]'::jsonb
),
(
  'mit-africa',
  'MIT-Africa Program',
  'Massachusetts Institute of Technology',
  'Full Tuition',
  'USD',
  'Merit-Based',
  '2024-11-30',
  'United States',
  'Graduate',
  'Scholarships for African students pursuing STEM fields at MIT.',
  '["African citizenship", "STEM background", "Academic excellence"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392704/portrait-young-woman-with-laptop-hands-outside-school_yktf28.jpg',
  false,
  'field-based',
  'https://web.mit.edu/africa',
  'africa@mit.edu',
  '+1 617 253 1000',
  'MIT-Africa Program supports African students pursuing graduate studies in STEM fields at MIT.',
  '["Full tuition", "Stipend", "Health insurance", "Research funding"]'::jsonb,
  '["African citizenship", "STEM background", "Academic excellence", "Admission to MIT"]'::jsonb,
  '["Apply to MIT", "Complete MIT-Africa application", "Submit research proposal", "Attend interview"]'::jsonb,
  '["MIT application", "Academic transcripts", "Research proposal", "Recommendation letters", "GRE scores"]'::jsonb,
  '["Academic excellence", "Research potential", "STEM alignment", "Impact potential"]'::jsonb,
  '["Full tuition", "Stipend", "Health insurance", "Research funding"]'::jsonb,
  '2-5 years depending on program',
  'Renewable based on performance',
  '["Engineering & Technology", "Natural Sciences", "Computer Science & IT"]'::jsonb,
  '[]'::jsonb
),
(
  'who-health',
  'WHO Scholarships for Health Sciences',
  'World Health Organization',
  'Full Coverage',
  'USD',
  'Merit-Based',
  '2024-12-15',
  'Global',
  'Graduate',
  'Scholarships for students pursuing public health and medical research.',
  '["Health sciences background", "Commitment to public health", "Academic excellence"]'::jsonb,
  true,
  'https://res.cloudinary.com/dsypclqxk/image/upload/v1763392935/19234_tbfzs9.jpg',
  false,
  'field-based',
  'https://www.who.int',
  'scholarships@who.int',
  '+41 22 791 21 11',
  'WHO offers scholarships for students pursuing public health and medical research programs.',
  '["Full tuition", "Monthly stipend", "Research funding", "Travel allowance"]'::jsonb,
  '["Health sciences background", "Commitment to public health", "Academic excellence", "Research proposal"]'::jsonb,
  '["Check WHO website", "Complete application", "Submit research proposal", "Attend interview"]'::jsonb,
  '["Completed application", "Academic transcripts", "Research proposal", "Recommendation letters", "Health sciences background proof"]'::jsonb,
  '["Academic merit", "Public health commitment", "Research quality", "Impact potential"]'::jsonb,
  '["Full tuition", "Monthly stipend", "Research funding", "Travel allowance"]'::jsonb,
  '1-3 years',
  'Renewable based on performance',
  '["Health Sciences & Medicine"]'::jsonb,
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  amount = EXCLUDED.amount,
  currency = EXCLUDED.currency,
  category = EXCLUDED.category,
  deadline = EXCLUDED.deadline,
  location = EXCLUDED.location,
  level = EXCLUDED.level,
  description = EXCLUDED.description,
  requirements = EXCLUDED.requirements,
  verified = EXCLUDED.verified,
  image_url = EXCLUDED.image_url,
  featured = EXCLUDED.featured,
  source = EXCLUDED.source,
  website = EXCLUDED.website,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  full_description = EXCLUDED.full_description,
  benefits = EXCLUDED.benefits,
  eligibility = EXCLUDED.eligibility,
  application_process = EXCLUDED.application_process,
  documents = EXCLUDED.documents,
  selection_criteria = EXCLUDED.selection_criteria,
  coverage_details = EXCLUDED.coverage_details,
  duration = EXCLUDED.duration,
  renewability = EXCLUDED.renewability,
  field_of_study = EXCLUDED.field_of_study,
  faqs = EXCLUDED.faqs,
  updated_at = NOW();

-- ============================================
-- Verification Query
-- ============================================
-- Run this to verify all scholarships were inserted
SELECT 
  source,
  COUNT(*) as count
FROM scholarships
GROUP BY source
ORDER BY source;